---
title: "coronavirus-job-losses"
author: "Joe Yerardi"
date: "3/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Set working directory
setwd("/home/joe/Projects/coronavirus-job-losses//")
```

```{r import packages, echo = FALSE}
library("dplyr")
library("ggplot2")
library("htmltools")
library("purrr")
library("readr")
library("sf")
library("stringr")
library("tidyr")
library("leaflet")
library("tigris")
```

```{r import data, echo = FALSE}
# Import (BLS's Quarterly Census of Employment and Wages (QCEW))[https://data.bls.gov/cew/apps/data_views/data_views.htm#tab=Tables] data

# Total Covered, 10 Total, all industries, All Counties 2019 Third Quarter, All establishment sizes
all_industries <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/10.csv") %>% 
  filter(own_code == 0 & agglvl_code == 70 & is.na(disclosure_code)) %>% # All ownership types, county-level, un-suppressed
  select(area_fips, september_employment_all_industries = month3_emplvl, total_qtrly_wages_all_industries = total_qtrly_wages)

# Private, NAICS 481 Air transportation, All Counties, 2019 Third Quarter, All establishment sizes
air_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/481.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 482 Rail transportation, All Counties, 2019 Third Quarter, All establishment sizes
rail_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/482.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 483 Water transportation, All Counties, 2019 Third Quarter, All establishment sizes
water_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/483.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 485 Transit and ground passenger transportation, All Counties, 2019 Third Quarter, All establishment sizes
transit_ground_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/485.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 487 Scenic and sightseeing transportation, All Counties, 2019 Third Quarter, All establishment sizes
scenic_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/487.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 488 Support activities for transportation, All Counties, 2019 Third Quarter, All establishment sizes
support_activities_transport <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/488.csv") %>% 
  filter(own_code == 5 & agglvl_code == 75) %>% # Privately-owned, county-level
  select(area_fips, september_employment = month3_emplvl, total_qtrly_wages)

# Private, NAICS 71 Arts, entertainment, and recreation, All Counties, 2019 Third Quarter, All establishment sizes
arts_ent_rec <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/71.csv") %>% 
  filter(own_code == 5 & agglvl_code == 74) %>% # Privately-owned, county-level
  select(area_fips, september_employment_arts_ent_rec = month3_emplvl, total_qtrly_wages_arts_ent_rec = total_qtrly_wages, september_employment_lq_arts_ent_rec = lq_month3_emplvl, total_qtrly_wages_lq_arts_ent_rec = lq_total_qtrly_wages)

# Private, NAICS 72 Accommodation and food services, All Counties, 2019 Third Quarter, All establishment sizes
accom_food <- read_csv("https://data.bls.gov/cew/data/api/2019/3/industry/72.csv") %>% 
  filter(own_code == 5 & agglvl_code == 74) %>% # Privately-owned, county-level
  select(area_fips, september_employment_accom_food = month3_emplvl, total_qtrly_wages_accom_food = total_qtrly_wages, september_employment_lq_accom_food = lq_month3_emplvl, total_qtrly_wages_lq_accom_food = lq_total_qtrly_wages)

# Import 2017 health insurance data from the Census Bureau's (Small Area Health Insurance Estimates)[https://www.census.gov/programs-surveys/sahie/data/datasets.html]
health_insurance <- read_csv("data/sahie_2017.csv", skip = 79) %>% 
  filter(geocat == "50" & (iprcat == "0" | iprcat == "5") & (agecat == "0" | agecat == "3") & sexcat == "0") %>% 
  mutate(area_fips = paste0(statefips, countyfips)) %>% 
  # Reshape the data from "long" to "wide" format
  pivot_wider(id_cols = area_fips,
              names_from = c("iprcat", "agecat"),
              values_from = c("NUI", "PCTUI")) %>% 
  select(area_fips,
         num_uninsured_total = NUI_0_0,
         num_uninsured_138_400_poverty = NUI_5_0,
         num_uninsured_age_50_up = NUI_0_3,
         pct_uninsured_total = PCTUI_0_0,
         pct_uninsured_138_400_poverty = PCTUI_5_0,
         pct_uninsured_age_50_up = PCTUI_0_3)

# Import 2018 county population data from the Census Bureau's American Community Survey
county_pops <- read_csv("data/ACSDT5Y2018.B01003_data_with_overlays_2020-03-23T201239.csv")
# Drop the duplicate header row
county_pops <- county_pops[-1,]
# Convert the population column to numeric
county_pops$B01003_001E <- as.numeric(as.character(county_pops$B01003_001E))
# Create separate county and state columns
county_pops$county = separate(data = county_pops, col = NAME, into = c("county", "state"), sep = ", ", remove = T)[, 2]
county_pops$state = separate(data = county_pops, col = NAME, into = c("county", "state"), sep = ", ", remove = T)[, 3]
# Drop unnecessary columns
county_pops <- county_pops %>% 
  mutate(area_fips = substr(GEO_ID, 10, 15),
         county = unlist(county, use.names = T),
         state = unlist(state, use.names = T)) %>% 
  select(area_fips, county, state, population = B01003_001E)
```

```{r reshape data, echo = FALSE}
# Set variables for nationwide employment and wages figures
us_september_employment_transportation = 507269 + 392 + 68165 + 499236 + 39260 + 742948
us_total_qtrly_wages_transportation = 11047760728 + 6158160 + 1428003244 + 4492040626 + 373221276 + 10654939055

us_september_employment_arts_ent_rec = 2467659
us_total_qtrly_wages_arts_ent_rec = 24359411562

us_september_employment_accom_food = 14108318
us_total_qtrly_wages_accom_food = 80885211645

us_september_employment_selected_industries = us_september_employment_transportation + us_september_employment_arts_ent_rec + us_september_employment_accom_food
us_total_qtrly_wages_selected_industries = us_total_qtrly_wages_transportation + us_total_qtrly_wages_arts_ent_rec + us_total_qtrly_wages_accom_food

us_september_employment_all_industries = 148556525
us_total_qtrly_wages_all_industries = 2101499510734

# Join the transportation data frames for the three-digit NAICS categories together and with the other data frame
transportation <- list(air_transport, rail_transport, water_transport, transit_ground_transport, scenic_transport, support_activities_transport, all_industries, county_pops, health_insurance) %>% 
  reduce(full_join, by = "area_fips") %>% 
  mutate(september_employment_transportation = select(., 2, 4, 6, 8, 10, 12) %>% 
           rowSums(na.rm = T),
         total_qtrly_wages_transportation = select(., 3, 5, 7, 9, 11, 13) %>% 
           rowSums(na.rm = T),
         september_jobs_per_thousand_transportation = round(september_employment_transportation / september_employment_all_industries * 1000, digits = 0),
         total_qtrly_wages_lc_transportation = round(total_qtrly_wages_transportation / total_qtrly_wages_all_industries, digits = 2),
         september_employment_lq_transportation = round((september_employment_transportation / september_employment_all_industries) / (us_september_employment_transportation / us_september_employment_all_industries), digits = 2),
         total_qtrly_wages_lq_transportation = round((total_qtrly_wages_transportation / total_qtrly_wages_all_industries) / (us_total_qtrly_wages_transportation / us_total_qtrly_wages_all_industries), digits = 2)) %>% 
  filter(!is.na(september_jobs_per_thousand_transportation)) %>% 
  select(area_fips,
         county,
         state,
         population,
         pct_uninsured_total,
         pct_uninsured_138_400_poverty,
         pct_uninsured_age_50_up,
         september_employment_transportation,
         total_qtrly_wages_transportation,
         september_employment_all_industries,
         total_qtrly_wages_all_industries,
         september_jobs_per_thousand_transportation,
         total_qtrly_wages_lc_transportation,
         september_employment_lq_transportation,
         total_qtrly_wages_lq_transportation)

# Join the arts, entertainment and recreation industry data frame with the other data frames
arts_ent_rec <- list(arts_ent_rec, all_industries, county_pops, health_insurance) %>% 
  reduce(full_join, by = "area_fips") %>% 
  mutate(september_jobs_per_thousand_arts_ent_rec = round(september_employment_arts_ent_rec / september_employment_all_industries * 1000, digits = 0),
         total_qtrly_wages_lc_arts_ent_rec = round(total_qtrly_wages_arts_ent_rec / total_qtrly_wages_all_industries, digits = 2)) %>% 
  filter(!is.na(september_jobs_per_thousand_arts_ent_rec)) %>% 
  select(area_fips,
         county,
         state,
         population,
         pct_uninsured_total,
         pct_uninsured_138_400_poverty,
         pct_uninsured_age_50_up,
         september_employment_arts_ent_rec,
         total_qtrly_wages_arts_ent_rec,
         september_employment_all_industries,
         total_qtrly_wages_all_industries,
         september_jobs_per_thousand_arts_ent_rec,
         total_qtrly_wages_lc_arts_ent_rec,
         september_employment_lq_arts_ent_rec,
         total_qtrly_wages_lq_arts_ent_rec)

# Join the accomodation and food services industry data frame with the other data frames
accom_food <- list(accom_food, all_industries, county_pops, health_insurance) %>% 
  reduce(full_join, by = "area_fips") %>% 
  mutate(september_jobs_per_thousand_accom_food = round(september_employment_accom_food / september_employment_all_industries * 1000, digits = 0),
         total_qtrly_wages_lc_accom_food = round(total_qtrly_wages_accom_food / total_qtrly_wages_all_industries, digits = 2)) %>% 
  filter(!is.na(september_jobs_per_thousand_accom_food)) %>% 
  select(area_fips,
         county,
         state,
         population,
         pct_uninsured_total,
         pct_uninsured_138_400_poverty,
         pct_uninsured_age_50_up,
         september_employment_accom_food,
         total_qtrly_wages_accom_food,
         september_employment_all_industries,
         total_qtrly_wages_all_industries,
         september_jobs_per_thousand_accom_food,
         total_qtrly_wages_lc_accom_food,
         september_employment_lq_accom_food,
         total_qtrly_wages_lq_accom_food)

# Join all the selected industries data frames together
selected_industries <- list(transportation, arts_ent_rec, accom_food) %>% 
  reduce(full_join, by = "area_fips") %>% 
  mutate(september_employment_selected_industries = select(., 8, 22, 36) %>% 
           rowSums(na.rm = T),
         total_qtrly_wages_selected_industries = select(., 9, 23, 37) %>% 
           rowSums(na.rm = T),
         september_jobs_per_thousand_selected_industries = round(september_employment_selected_industries / september_employment_all_industries * 1000, digits = 0),
         total_qtrly_wages_lc_selected_industries = round(total_qtrly_wages_selected_industries / total_qtrly_wages_all_industries, digits = 2),
         september_employment_lq_selected_industries = round((september_employment_selected_industries / september_employment_all_industries) / (us_september_employment_selected_industries / us_september_employment_all_industries), digits = 2),
         total_qtrly_wages_lq_selected_industries = round((total_qtrly_wages_selected_industries / total_qtrly_wages_all_industries) / (us_total_qtrly_wages_selected_industries / us_total_qtrly_wages_all_industries), digits = 2)) %>% 
  filter(!is.na(september_jobs_per_thousand_selected_industries)) %>% 
  select(area_fips,
         county,
         state,
         population,
         pct_uninsured_total,
         pct_uninsured_138_400_poverty,
         pct_uninsured_age_50_up,
         september_employment_selected_industries,
         total_qtrly_wages_selected_industries,
         september_employment_all_industries,
         total_qtrly_wages_all_industries,
         september_jobs_per_thousand_selected_industries,
         total_qtrly_wages_lc_selected_industries,
         september_employment_lq_selected_industries,
         total_qtrly_wages_lq_selected_industries)

# Join the health insurance and county population data frames
health_insurance <- health_insurance %>% 
  full_join(county_pops, by = "area_fips") %>% 
  select(area_fips,
         county,
         state,
         population,
         num_uninsured_total,
         num_uninsured_138_400_poverty,
         num_uninsured_age_50_up,
         pct_uninsured_total,
         pct_uninsured_138_400_poverty,
         pct_uninsured_age_50_up)

# Export the data
write_csv(transportation, "data/exported/transportation.csv")
write_csv(arts_ent_rec, "data/exported/arts_ent_rec.csv")
write_csv(accom_food, "data/exported/accom_food.csv")
write_csv(selected_industries, "data/exported/selected_industries.csv")
write_csv(health_insurance, "data/exported/health_insurance.csv")
```

```{r map data, echo = FALSE}
# Import US counties shapefile
counties <- counties(cb = T)

# Join the shapefile to each of the industry data frames plus the health insurance data frame
transportation_geo <- geo_join(counties, transportation, "GEOID", "area_fips", how = "inner")
arts_ent_rec_geo <- geo_join(counties, arts_ent_rec, "GEOID", "area_fips", how = "inner")
accom_food_geo <- geo_join(counties, accom_food, "GEOID", "area_fips", how = "inner")
selected_industries_geo <- geo_join(counties, selected_industries, "GEOID", "area_fips", how = "inner")
health_insurance_geo <- geo_join(counties, health_insurance, "GEOID", "area_fips", how = "inner")

# Set variables for the color palettes and popup texts
transportation_geo_pal <- colorNumeric("Reds", domain = transportation_geo$september_jobs_per_thousand_transportation)
transportation_geo_popup_text <- paste0(transportation_geo$county, " has ", as.character(transportation_geo$september_jobs_per_thousand_transportation)," transportation jobs per thousand total jobs.")

arts_ent_rec_geo_pal <- colorNumeric("Reds", domain = arts_ent_rec_geo$september_jobs_per_thousand_arts_ent_rec)
arts_ent_rec_geo_popup_text <- paste0(arts_ent_rec_geo$county, " has ", as.character(arts_ent_rec_geo$september_jobs_per_thousand_arts_ent_rec)," arts, entertainment and recreation jobs per thousand total jobs.")

accom_food_geo_pal <- colorNumeric("Reds", domain = accom_food_geo$september_jobs_per_thousand_accom_food)
accom_food_geo_popup_text <- paste0(accom_food_geo$county, " has ", as.character(accom_food_geo$september_jobs_per_thousand_accom_food)," accomodation and food services jobs per thousand total jobs.")

selected_industries_geo_pal <- colorNumeric("Reds", domain = selected_industries_geo$september_jobs_per_thousand_selected_industries)
selected_industries_geo_popup_text <- paste0(selected_industries_geo$county, " has ", as.character(selected_industries_geo$september_jobs_per_thousand_selected_industries)," selected industry obs per thousand total jobs.")

health_insurance_geo_pal <- colorNumeric("Reds", domain = health_insurance_geo$pct_uninsured_total)
health_insurance_geo_popup_text <- paste0(health_insurance_geo$county, " has a ", as.character(health_insurance_geo$pct_uninsured_total),"% uninsured rate.")

# Map the data frames
transportation_geo_map <- transportation_geo %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(fillColor = ~ transportation_geo_pal(transportation_geo$september_jobs_per_thousand_transportation),
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              stroke = F,
              popup = ~ transportation_geo_popup_text) %>% 
  addLegend(pal = transportation_geo_pal,
            values = transportation_geo$september_jobs_per_thousand_transportation,
            position = "bottomleft",
            title = "Jobs per thousand in the</br/>transportation industry")

arts_ent_rec_geo_map <- arts_ent_rec_geo %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(fillColor = ~ arts_ent_rec_geo_pal(arts_ent_rec_geo$september_jobs_per_thousand_arts_ent_rec),
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              stroke = F,
              popup = ~ arts_ent_rec_geo_popup_text) %>% 
  addLegend(pal = arts_ent_rec_geo_pal,
            values = arts_ent_rec_geo$september_jobs_per_thousand_arts_ent_rec,
            position = "bottomleft",
            title = "Jobs per thousand in the arts,</br/>entertainment and recreation industry")

accom_food_geo_map <- accom_food_geo %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(fillColor = ~ accom_food_geo_pal(accom_food_geo$september_jobs_per_thousand_accom_food),
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              stroke = F,
              popup = ~ accom_food_geo_popup_text) %>% 
  addLegend(pal = accom_food_geo_pal,
            values = accom_food_geo$september_jobs_per_thousand_accom_food,
            position = "bottomleft",
            title = "Jobs per thousand in the accommodation</br/>and food services industry")

selected_industries_geo_map <- selected_industries_geo %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(fillColor = ~ selected_industries_geo_pal(selected_industries_geo$september_jobs_per_thousand_selected_industries),
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              stroke = F,
              popup = ~ selected_industries_geo_popup_text) %>% 
  addLegend(pal = selected_industries_geo_pal,
            values = selected_industries_geo$september_jobs_per_thousand_selected_industries,
            position = "bottomleft",
            title = "Jobs per thousand in </br/>selected industries")

health_insurance_geo_map <- health_insurance_geo %>% 
  leaflet() %>% 
  addTiles() %>% 
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(fillColor = ~ health_insurance_geo_pal(health_insurance_geo$pct_uninsured_total),
              fillOpacity = 0.5,
              smoothFactor = 0.5,
              stroke = F,
              popup = ~ health_insurance_geo_popup_text) %>% 
  addLegend(pal = health_insurance_geo_pal,
            values = health_insurance_geo$pct_uninsured_total,
            position = "bottomleft",
            title = "Under-65 uninsured rate")

# Export the maps
save_html(transportation_geo_map, file = paste0(getwd(),"/maps/transportation_geo_map.html"), background = "white")
save_html(arts_ent_rec_geo_map, file = paste0(getwd(),"/maps/arts_ent_rec_geo_map.html"), background = "white")
save_html(accom_food_geo_map, file = paste0(getwd(),"/maps/accom_food_geo_map.html"), background = "white")
save_html(selected_industries_geo_map, file = paste0(getwd(),"/maps/selected_industries_geo_map.html"), background = "white")
save_html(health_insurance_geo_map, file = paste0(getwd(),"/maps/health_insurance_geo_map.html"), background = "white")
```

```{r analyze the data, echo = FALSE}
# Which counties are most reliant on these industries for jobs?
most_reliant <- selected_industries %>% 
  filter(september_employment_lq_selected_industries > 1)

# Which 100 counties have the highest rate of uninsured residents under the age of 65?
most_uninsured <- health_insurance %>% 
  filter(pct_uninsured_total > 10) # [2018 national rate of uninsurance among residents under the age of 65 = 10%](https://www.census.gov/data/tables/2019/demo/health-insurance/p60-267.html)

# Which counties meet both conditions?
most_reliant_uninsured <- most_reliant %>% 
  inner_join(most_uninsured, by = "area_fips") %>% 
  select(area_fips,
         county = county.x,
         state = state.x,
         population = population.x,
         num_uninsured_total = num_uninsured_total,
         pct_uninsured_total = pct_uninsured_total.x,
         september_employment_selected_industries,
         september_jobs_per_thousand_selected_industries,
         september_employment_lq_selected_industries)
```
